package org.example.project.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import org.example.project.data.models.ProductCategory
import org.example.project.data.repositories.UploadedProductAsset
import org.example.project.utils.openFileChooser
import kotlinx.coroutines.launch
import java.io.File
import java.time.LocalDate
import java.time.format.DateTimeFormatter
import androidx.compose.material3.DatePicker
import androidx.compose.material3.DatePickerDialog
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.rememberDatePickerState
import org.example.project.data.models.categoryDisplayPath
import org.example.project.data.models.childProductCategories
import org.example.project.data.models.selectedCategoryGroupId
import org.example.project.data.models.topLevelProductCategories

/**
 * Data class keeps the full payload expected by backend, while the desktop
 * wizard only exposes the fields needed for the DATN e-commerce flow.
 */
data class CompleteProductFormData(
    // Group 1: Basic Information
    val productName: String = "",
    val sku: String = "",
    val skuAutoGenerated: Boolean = false,
    val categoryId: String = "",
    val unit: String = "Hộp",
    val brand: String = "",
    val manufacturer: String = "",
    val origin: String = "",
    val shortDescription: String = "",
    val fullDescription: String = "",

    // Group 2: Healthcare Specific
    val registrationNumber: String = "",
    val riskClassification: String = "A",

    // Group 3: Pricing & Images
    val contactForPrice: Boolean = false,
    val price: Double = 0.0,
    val originalPrice: Double? = null,
    val discountPct: Int = 0,
    val rewardPoints: Int = 0,
    val productImages: List<ProductImageData> = emptyList(),
    
    // Group 4: Inventory
    val firstStockData: StockData? = null,
    
    // Group 5: Certificates
    val certificates: List<CertificateData> = emptyList()
)

data class ProductImageData(
    val url: String = "",
    val mediaType: String = "IMAGE",
    val publicId: String? = null,
    val sortOrder: Int = 0
)

data class StockData(
    val mfgDate: String = "",
    val expDate: String = "",
    val quantityOnHand: Int = 0,
    val importPrice: Double = 0.0
)

data class CertificateData(
    val type: String = "",
    val name: String = "",
    val fileUrl: String = "",
    val publicId: String? = null,
    val fileType: String = "IMAGE",
    val resourceType: String = "image",
    val thumbnailUrl: String? = null,
    val issuer: String = ""
)

@Composable
fun CompleteProductFormStepper(
    categories: List<ProductCategory> = emptyList(),
    onUploadProductMedia: suspend (File, String) -> Result<UploadedProductAsset>,
    onUploadCertificate: suspend (File) -> Result<UploadedProductAsset>,
    onDeleteUploadedAsset: suspend (String, String) -> Result<Unit>,
    onSave: (CompleteProductFormData) -> Unit,
    onCancel: () -> Unit,
    onGenerateSku: ((categoryId: String) -> String)? = null,
    initialData: CompleteProductFormData = CompleteProductFormData()
) {
    var formData by remember { mutableStateOf(initialData) }
    var currentStep by remember { mutableStateOf(0) }
    val scope = rememberCoroutineScope()
    var isCleaningUp by remember { mutableStateOf(false) }
    var cleanupError by remember { mutableStateOf<String?>(null) }
    val wizardSteps = listOf(
        "Thông tin bán hàng",
        "Giá & hình ảnh",
        "Kho & giấy tờ"
    )

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp)
    ) {
        // Step indicator
        StepIndicator(currentStep, wizardSteps)
        
        Spacer(modifier = Modifier.height(24.dp))

        cleanupError?.let { message ->
            Text(
                text = message,
                color = MaterialTheme.colorScheme.error,
                style = MaterialTheme.typography.bodySmall
            )
            Spacer(modifier = Modifier.height(12.dp))
        }

        // Step content
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f)
        ) {
            when (currentStep) {
                0 -> Step1BasicInfo(
                    data = formData,
                    categories = categories,
                    onGenerateSku = onGenerateSku,
                    onUpdate = { formData = it }
                )
                1 -> Step3PricingImages(
                    data = formData,
                    onUploadProductMedia = onUploadProductMedia,
                    onDeleteUploadedAsset = onDeleteUploadedAsset,
                    onUpdate = { formData = it }
                )
                2 -> Step2HealthcareSpecific(
                    data = formData,
                    onUploadCertificate = onUploadCertificate,
                    onDeleteUploadedAsset = onDeleteUploadedAsset,
                    onUpdate = { formData = it }
                )
            }
        }
        
        Spacer(modifier = Modifier.height(24.dp))
        
        // Navigation buttons
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween
        ) {
            Button(
                onClick = { if (currentStep > 0) currentStep-- },
                enabled = currentStep > 0 && !isCleaningUp,
                colors = ButtonDefaults.buttonColors(
                    containerColor = MaterialTheme.colorScheme.secondary
                )
            ) {
                Icon(Icons.Default.ArrowBack, contentDescription = null)
                Spacer(modifier = Modifier.width(8.dp))
                Text("Quay lại")
            }
            
            Row(
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                TextButton(
                    onClick = {
                        scope.launch {
                            isCleaningUp = true
                            cleanupError = null
                            val cleanupResult = cleanupWizardUploads(formData, onDeleteUploadedAsset)
                            isCleaningUp = false
                            cleanupResult.fold(
                                onSuccess = { onCancel() },
                                onFailure = { error ->
                                    cleanupError = error.message ?: "Khong the don dep tep da tai len"
                                }
                            )
                        }
                    },
                    enabled = !isCleaningUp
                ) {
                    Text("Hủy")
                }
                
                Button(
                    onClick = {
                        cleanupError = null
                        if (currentStep < wizardSteps.size - 1) {
                            if (isStepValid(currentStep, formData)) {
                                currentStep++
                            }
                        } else {
                            if (isFormComplete(formData)) {
                                onSave(formData)
                            }
                        }
                    },
                    colors = ButtonDefaults.buttonColors(
                        containerColor = MaterialTheme.colorScheme.primary
                    ),
                    enabled = !isCleaningUp
                ) {
                    Text(if (currentStep == wizardSteps.size - 1) "Lưu sản phẩm" else "Tiếp theo")
                    if (currentStep < wizardSteps.size - 1) {
                        Spacer(modifier = Modifier.width(8.dp))
                        Icon(Icons.Default.ArrowForward, contentDescription = null)
                    }
                }
            }
        }
    }
}

@Composable
private fun StepIndicator(currentStep: Int, steps: List<String>) {
    Column {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(4.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            steps.forEachIndexed { index, step ->
                StepCircle(
                    number = index + 1,
                    isActive = index == currentStep,
                    isCompleted = index < currentStep,
                    modifier = Modifier.weight(1f)
                )
                
                if (index < steps.size - 1) {
                    Divider(
                        modifier = Modifier
                            .weight(0.5f)
                            .height(2.dp),
                        color = if (index < currentStep)
                            MaterialTheme.colorScheme.primary
                        else
                            Color.LightGray
                    )
                }
            }
        }
        
        Spacer(modifier = Modifier.height(8.dp))
        
        Text(
            text = steps[currentStep],
            style = MaterialTheme.typography.headlineSmall,
            fontWeight = FontWeight.Bold,
            modifier = Modifier.align(Alignment.CenterHorizontally)
        )
    }
}

@Composable
private fun StepCircle(
    number: Int,
    isActive: Boolean,
    isCompleted: Boolean,
    modifier: Modifier = Modifier
) {
    val backgroundColor = when {
        isCompleted -> MaterialTheme.colorScheme.primary
        isActive -> MaterialTheme.colorScheme.primaryContainer
        else -> Color.LightGray
    }
    
    val contentColor = when {
        isCompleted -> Color.White
        isActive -> MaterialTheme.colorScheme.onPrimaryContainer
        else -> Color.Gray
    }
    
    Box(
        modifier = modifier
            .size(40.dp)
            .background(backgroundColor, shape = RoundedCornerShape(20.dp)),
        contentAlignment = Alignment.Center
    ) {
        if (isCompleted) {
            Icon(
                Icons.Default.Check,
                contentDescription = null,
                tint = Color.White,
                modifier = Modifier.size(24.dp)
            )
        } else {
            Text(
                text = number.toString(),
                color = contentColor,
                fontWeight = FontWeight.Bold,
                fontSize = 14.sp
            )
        }
    }
}

// ============================================================================
// STEP 1: BASIC INFORMATION (Thông tin cơ bản)
// ============================================================================
@Composable
private fun Step1BasicInfo(
    data: CompleteProductFormData,
    categories: List<ProductCategory>,
    onGenerateSku: ((categoryId: String) -> String)? = null,
    onUpdate: (CompleteProductFormData) -> Unit
) {
    val groups = remember(categories) { topLevelProductCategories(categories) }
    val selectedGroupId = selectedCategoryGroupId(categories, data.categoryId)
    val selectedGroup = groups.firstOrNull { it.id == selectedGroupId }
    val children = remember(categories, selectedGroupId) {
        childProductCategories(categories, selectedGroupId)
    }
    val selectedChild = children.firstOrNull { it.id == data.categoryId }

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(12.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        item {
            Text(
                "Bước 1: Thông tin cơ bản sản phẩm",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        }
        
        // Tên sản phẩm (Required)
        item {
            FormField(
                label = "Tên sản phẩm *",
                value = data.productName,
                onValueChange = { onUpdate(data.copy(productName = it)) },
                placeholder = "VD: Máy đo huyết áp OMRON HEM-7120",
                singleLine = true
            )
        }

        item {
            FormField(
                label = "SKU / mã nội bộ",
                value = data.sku,
                onValueChange = { onUpdate(data.copy(sku = it, skuAutoGenerated = false)) },
                placeholder = "VD: OMR-HEM-7120",
                singleLine = true
            )
        }
        
        // Category
        item {
            DropdownField(
                label = "Nhóm danh mục *",
                value = selectedGroup?.displayName ?: "Chọn nhóm danh mục",
                options = groups.map { it.displayName to it.id },
                onSelect = { selectedId ->
                    val firstChild = childProductCategories(categories, selectedId).firstOrNull()
                    val newCategoryId = firstChild?.id ?: selectedId
                    if (data.skuAutoGenerated || data.sku.isBlank()) {
                        val newSku = onGenerateSku?.invoke(newCategoryId)
                        onUpdate(data.copy(categoryId = newCategoryId, sku = newSku ?: data.sku, skuAutoGenerated = newSku != null))
                    } else {
                        onUpdate(data.copy(categoryId = newCategoryId))
                    }
                }
            )
        }

        if (selectedGroup != null && children.isNotEmpty()) {
            item {
                DropdownField(
                    label = "Danh mục con",
                    value = selectedChild?.displayName
                        ?: if (data.categoryId == selectedGroup.id) "Nhóm chung: ${selectedGroup.displayName}" else "Chọn danh mục con",
                    options = listOf("Nhóm chung: ${selectedGroup.displayName}" to selectedGroup.id) +
                        children.map { it.displayName to it.id },
                    onSelect = { selectedId ->
                        if (data.skuAutoGenerated || data.sku.isBlank()) {
                            val newSku = onGenerateSku?.invoke(selectedId)
                            onUpdate(data.copy(categoryId = selectedId, sku = newSku ?: data.sku, skuAutoGenerated = newSku != null))
                        } else {
                            onUpdate(data.copy(categoryId = selectedId))
                        }
                    }
                )
                val path = categoryDisplayPath(categories, data.categoryId)
                if (path.isNotBlank()) {
                    Spacer(modifier = Modifier.height(4.dp))
                    Text(
                        path,
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        }

        item {
            DropdownField(
                label = "Phân loại thiết bị *",
                value = "Loại ${data.riskClassification}",
                options = listOf(
                    "Loại A - bán online" to "A",
                    "Loại B - bán online" to "B",
                    "Loại C - cần tư vấn/ký kết" to "C",
                    "Loại D - cần tư vấn/ký kết" to "D"
                ),
                onSelect = { selectedRisk ->
                    onUpdate(data.copy(riskClassification = selectedRisk))
                }
            )
        }

        // Unit (Required)
        item {
            DropdownField(
                label = "Đơn vị tính *",
                value = data.unit,
                options = listOf(
                    "Hộp" to "Hộp",
                    "Cái" to "Cái",
                    "Vỉ" to "Vỉ",
                    "Cuộn" to "Cuộn",
                    "Viên" to "Viên",
                    "Chai" to "Chai",
                    "Gói" to "Gói"
                ),
                onSelect = { onUpdate(data.copy(unit = it)) }
            )
        }
        
        // Brand
        item {
            FormField(
                label = "Thương hiệu",
                value = data.brand,
                onValueChange = { onUpdate(data.copy(brand = it)) },
                placeholder = "VD: OMRON, 3M",
                singleLine = true
            )
        }
        
        // Origin
        item {
            FormField(
                label = "Xuất xứ",
                value = data.origin,
                onValueChange = { onUpdate(data.copy(origin = it)) },
                placeholder = "VD: Nhật Bản, Việt Nam, Hàn Quốc",
                singleLine = true
            )
        }
        
        item {
            FormField(
                label = "Mô tả sản phẩm",
                value = data.shortDescription,
                onValueChange = { onUpdate(data.copy(shortDescription = it, fullDescription = it)) },
                placeholder = "Mô tả ngắn gọn đặc điểm, công dụng, lưu ý",
                maxLines = 4
            )
        }

        item {
            FormField(
                label = "Nhà sản xuất",
                value = data.manufacturer,
                onValueChange = { onUpdate(data.copy(manufacturer = it)) },
                placeholder = "VD: Omron Healthcare, Công ty thiết bị y tế ABC",
                singleLine = true
            )
        }
    }
}

@Composable
private fun Step2HealthcareSpecific(
    data: CompleteProductFormData,
    onUploadCertificate: suspend (File) -> Result<UploadedProductAsset>,
    onDeleteUploadedAsset: suspend (String, String) -> Result<Unit>,
    onUpdate: (CompleteProductFormData) -> Unit
) {
    val scope = rememberCoroutineScope()
    val latestData by rememberUpdatedState(data)
    val license = data.certificates.firstOrNull()
    val stockData = data.firstStockData ?: StockData()
    var isUploading by remember { mutableStateOf(false) }
    var isDeletingFile by remember { mutableStateOf(false) }
    var uploadError by remember { mutableStateOf<String?>(null) }
    var showAdvanced by remember { mutableStateOf(false) }

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(12.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        item {
            Text(
                "Bước 3: Kho & giấy tờ",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        }

        item {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.secondaryContainer
                )
            ) {
                Text(
                    "Phần này có thể bỏ trống khi tạo nhanh. Có thể cập nhật tồn kho, hạn dùng và giấy tờ sau.",
                    modifier = Modifier.padding(12.dp),
                    style = MaterialTheme.typography.bodySmall
                )
            }
        }

        item {
            FormField(
                label = "Số lượng nhập ban đầu",
                value = if (stockData.quantityOnHand == 0) "" else stockData.quantityOnHand.toString(),
                onValueChange = {
                    onUpdate(data.copy(firstStockData = stockData.copy(quantityOnHand = it.toIntOrNull() ?: 0)))
                },
                placeholder = "VD: 100",
                keyboardType = KeyboardType.Number,
                singleLine = true
            )
        }

        item {
            DatePickerField(
                label = "Hạn sử dụng",
                value = stockData.expDate,
                onValueChange = {
                    onUpdate(data.copy(firstStockData = stockData.copy(expDate = it)))
                }
            )
        }

        item {
            FormField(
                label = "Số đăng ký lưu hành / số công bố",
                value = data.registrationNumber,
                onValueChange = { onUpdate(data.copy(registrationNumber = it)) },
                placeholder = "VD: 220001234/PCBA-HN",
                singleLine = true
            )
        }

        item {
            Surface(
                color = Color(0xFFF7FBF4),
                shape = MaterialTheme.shapes.medium,
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(12.dp),
                    verticalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Text("Giấy tờ sản phẩm", fontWeight = FontWeight.SemiBold)
                    Text(
                        license?.takeIf { it.fileUrl.isNotBlank() }?.let {
                            "Đã chọn: ${it.name.ifBlank { "File chứng nhận" }}"
                        } ?: "Có thể chọn ảnh/PDF giấy đăng ký, công bố hoặc chứng nhận chất lượng.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(
                            onClick = {
                                val file = openFileChooser(
                                    title = "Chọn giấy tờ sản phẩm",
                                    allowedExtensions = listOf(".jpg", ".jpeg", ".png", ".pdf", ".heic"),
                                    allowMultiple = false
                                ).firstOrNull() ?: return@Button

                                scope.launch {
                                    isUploading = true
                                    uploadError = null
                                    val previousLicense = latestData.certificates.firstOrNull()
                                    onUploadCertificate(file).fold(
                                        onSuccess = { uploaded ->
                                            val previousPublicId = previousLicense?.publicId
                                                ?.takeIf { it.isNotBlank() && it != uploaded.publicId }
                                            previousPublicId?.let { publicId ->
                                                onDeleteUploadedAsset(publicId, "image").onFailure { error ->
                                                    uploadError = error.message ?: "Đã thay file mới nhưng không thể xóa file cũ"
                                                }
                                            }

                                            val currentData = latestData
                                            val currentLicense = currentData.certificates.firstOrNull()
                                            onUpdate(
                                                currentData.withPrimaryCertificate(
                                                    (currentLicense ?: CertificateData(type = "MOH_LICENSE")).copy(
                                                        type = "MOH_LICENSE",
                                                        name = file.nameWithoutExtension,
                                                        fileUrl = uploaded.url,
                                                        publicId = uploaded.publicId,
                                                        fileType = uploaded.mediaType.ifBlank { "IMAGE" },
                                                        resourceType = uploaded.resourceType.ifBlank { "image" },
                                                        thumbnailUrl = if (uploaded.mediaType.equals("IMAGE", ignoreCase = true)) uploaded.url else null
                                                    )
                                                )
                                            )
                                        },
                                        onFailure = { error ->
                                            uploadError = error.message ?: "Không thể upload giấy tờ"
                                        }
                                    )
                                    isUploading = false
                                }
                            },
                            enabled = !isUploading && !isDeletingFile
                        ) {
                            Text(if (isUploading) "Đang upload..." else if (license?.fileUrl.isNullOrBlank()) "Chọn file" else "Đổi file")
                        }

                        if (!license?.fileUrl.isNullOrBlank()) {
                            TextButton(
                                onClick = {
                                    scope.launch {
                                        val currentData = latestData
                                        val currentLicense = currentData.certificates.firstOrNull() ?: return@launch
                                        isDeletingFile = true
                                        uploadError = null

                                        val cleanupResult = currentLicense.publicId
                                            ?.takeIf { it.isNotBlank() }
                                            ?.let { onDeleteUploadedAsset(it, currentLicense.resourceType.ifBlank { "image" }) }
                                            ?: Result.success(Unit)

                                        isDeletingFile = false
                                        cleanupResult.fold(
                                            onSuccess = {
                                                onUpdate(
                                                    currentData.copy(
                                                        certificates = currentData.certificates.drop(1)
                                                    )
                                                )
                                            },
                                            onFailure = { error ->
                                                uploadError = error.message ?: "Không thể xóa file đã tải lên"
                                            }
                                        )
                                    }
                                },
                                enabled = !isUploading && !isDeletingFile
                            ) {
                                Text(if (isDeletingFile) "Đang xóa..." else "Xóa file")
                            }
                        }
                    }
                }
            }
        }

        item {
            OutlinedButton(onClick = { showAdvanced = !showAdvanced }) {
                Text(if (showAdvanced) "Ẩn thông tin nâng cao" else "Thông tin nâng cao")
            }
        }

        if (showAdvanced) {
            item {
                DropdownField(
                    label = "Phân loại rủi ro",
                    value = data.riskClassification,
                    options = listOf(
                        "Loại A" to "A",
                        "Loại B" to "B",
                        "Loại C" to "C",
                        "Loại D" to "D"
                    ),
                    onSelect = { selectedRisk ->
                        onUpdate(data.copy(riskClassification = selectedRisk))
                    }
                )
            }

            if (data.riskClassification == "C" || data.riskClassification == "D") {
                item {
                    Surface(
                        color = MaterialTheme.colorScheme.tertiaryContainer,
                        shape = RoundedCornerShape(8.dp),
                        modifier = Modifier.fillMaxWidth()
                    ) {
                        Text(
                            "Loại ${data.riskClassification} chỉ tư vấn/ký kết tại Medstore, không bán online.",
                            modifier = Modifier.padding(12.dp),
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onTertiaryContainer
                        )
                    }
                }
            }

            item {
                DatePickerField(
                    label = "Ngày sản xuất",
                    value = stockData.mfgDate,
                    onValueChange = {
                        onUpdate(data.copy(firstStockData = stockData.copy(mfgDate = it)))
                    }
                )
            }

            item {
                FormField(
                    label = "Giá nhập (VND)",
                    value = if (stockData.importPrice == 0.0) "" else stockData.importPrice.toString(),
                    onValueChange = {
                        onUpdate(data.copy(firstStockData = stockData.copy(importPrice = it.toDoubleOrNull() ?: 0.0)))
                    },
                    placeholder = "VD: 750000",
                    keyboardType = KeyboardType.Decimal,
                    singleLine = true
                )
            }

        }

        uploadError?.let { message ->
            item {
                Text(
                    text = message,
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodySmall
                )
            }
        }
    }
}

@Composable
private fun Step3PricingImages(
    data: CompleteProductFormData,
    onUploadProductMedia: suspend (File, String) -> Result<UploadedProductAsset>,
    onDeleteUploadedAsset: suspend (String, String) -> Result<Unit>,
    onUpdate: (CompleteProductFormData) -> Unit
) {
    val scope = rememberCoroutineScope()
    val latestData by rememberUpdatedState(data)
    var isUploading by remember { mutableStateOf(false) }
    var deletingImageIndex by remember { mutableStateOf<Int?>(null) }
    var uploadError by remember { mutableStateOf<String?>(null) }

    LazyColumn(
        modifier = Modifier
            .fillMaxSize()
            .padding(12.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        item {
            Text(
                "Bước 2: Giá & hình ảnh",
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.Bold
            )
        }

        item {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(
                    checked = data.contactForPrice,
                    onCheckedChange = { onUpdate(data.copy(contactForPrice = it)) }
                )
                Spacer(modifier = Modifier.width(4.dp))
                Text("Giá liên hệ (ẩn giá, hiện nút \"Liên hệ\" trên app)")
            }
        }

        item {
            FormField(
                label = if (data.contactForPrice) "Giá bán (không hiển thị)" else "Giá bán (VND) *",
                value = if (data.price == 0.0) "" else data.price.toString(),
                onValueChange = { onUpdate(data.copy(price = it.toDoubleOrNull() ?: 0.0)) },
                placeholder = "VD: 850000",
                keyboardType = KeyboardType.Decimal,
                singleLine = true,
                enabled = !data.contactForPrice
            )
        }

        item {
            FormField(
                label = "Giá gốc / giá niêm yết (VND)",
                value = data.originalPrice?.toString() ?: "",
                onValueChange = { onUpdate(data.copy(originalPrice = it.toDoubleOrNull())) },
                placeholder = "VD: 950000",
                keyboardType = KeyboardType.Decimal,
                singleLine = true,
                enabled = !data.contactForPrice
            )
        }

        item {
            FormField(
                label = "Điểm thưởng cộng sau khi mua",
                value = if (data.rewardPoints == 0) "" else data.rewardPoints.toString(),
            onValueChange = { value ->
                onUpdate(data.copy(rewardPoints = value.filter { ch -> ch.isDigit() }.toIntOrNull() ?: 0))
            },
                placeholder = "VD: 200",
                keyboardType = KeyboardType.Number,
                singleLine = true
            )
            Text(
                text = "Điểm này được cộng khi đơn hoàn tất. Quy đổi khi thanh toán: 1 điểm = 1đ.",
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }

        item {
            Divider()
        }

        item {
            Row(
                modifier = Modifier.fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(
                    "Hình ảnh sản phẩm",
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.SemiBold
                )
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Button(
                        onClick = {
                            val files = openFileChooser(
                                title = "Chọn ảnh sản phẩm",
                                allowedExtensions = listOf(".jpg", ".jpeg", ".png", ".webp", ".heic"),
                                allowMultiple = true
                            )
                            if (files.isEmpty()) return@Button

                            scope.launch {
                                isUploading = true
                                uploadError = null
                                val uploaded = mutableListOf<ProductImageData>()

                                files.forEachIndexed { _, file ->
                                    val mediaType = detectMediaType(file)
                                    val result = onUploadProductMedia(file, mediaType)
                                    result.fold(
                                        onSuccess = { asset ->
                                            uploaded += ProductImageData(
                                                url = asset.url,
                                                mediaType = asset.mediaType,
                                                publicId = asset.publicId
                                            )
                                        },
                                        onFailure = { error ->
                                            if (uploadError == null) {
                                                uploadError = error.message ?: "Không thể upload tệp ${file.name}"
                                            }
                                        }
                                    )
                                }

                                if (uploaded.isNotEmpty()) {
                                    val currentData = latestData
                                    onUpdate(
                                        currentData.copy(
                                            productImages = reindexProductImages(currentData.productImages + uploaded)
                                        )
                                    )
                                }
                                isUploading = false
                            }
                        },
                        enabled = !isUploading && deletingImageIndex == null,
                        modifier = Modifier.height(32.dp),
                        contentPadding = PaddingValues(horizontal = 10.dp, vertical = 6.dp)
                    ) {
                        Icon(Icons.Default.Upload, contentDescription = null)
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(if (isUploading) "Đang tải..." else "Tải ảnh")
                    }
                }
            }
        }

        uploadError?.let { message ->
            item {
                Text(
                    text = message,
                    color = MaterialTheme.colorScheme.error,
                    style = MaterialTheme.typography.bodySmall
                )
            }
        }

        if (data.productImages.isEmpty()) {
            item {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.surfaceVariant
                    )
                ) {
                    Text(
                        "Chưa có hình ảnh. Tải ít nhất một ảnh để sản phẩm hiển thị đẹp trên app.",
                        modifier = Modifier.padding(16.dp),
                        style = MaterialTheme.typography.bodySmall
                    )
                }
            }
        } else {
            items(data.productImages.size) { index ->
                val image = data.productImages[index]
                val isDeletingThisImage = deletingImageIndex == index
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.surfaceVariant
                    )
                ) {
                    Column(
                        modifier = Modifier.padding(12.dp),
                        verticalArrangement = Arrangement.spacedBy(10.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                if (index == 0) "Ảnh bìa" else "Ảnh phụ ${index + 1}",
                                fontWeight = FontWeight.Bold
                            )
                            TextButton(
                                onClick = {
                                    scope.launch {
                                        val currentData = latestData
                                        val currentImage = currentData.productImages.getOrNull(index) ?: return@launch
                                        deletingImageIndex = index
                                        uploadError = null

                                        val cleanupResult = currentImage.publicId
                                            ?.takeIf { it.isNotBlank() }
                                            ?.let {
                                                onDeleteUploadedAsset(
                                                    it,
                                                    resourceTypeForMedia(currentImage.mediaType)
                                                )
                                            }
                                            ?: Result.success(Unit)

                                        deletingImageIndex = null
                                        cleanupResult.fold(
                                            onSuccess = {
                                                val refreshedData = latestData
                                                val updated = refreshedData.productImages.toMutableList()
                                                val removalIndex = currentImage.publicId
                                                    ?.let { publicId ->
                                                        updated.indexOfFirst { it.publicId == publicId }
                                                    }
                                                    ?: index.takeIf { it in updated.indices }

                                                if (removalIndex != null && removalIndex >= 0) {
                                                    updated.removeAt(removalIndex)
                                                    onUpdate(
                                                        refreshedData.copy(
                                                            productImages = reindexProductImages(updated)
                                                        )
                                                    )
                                                }
                                            },
                                            onFailure = { error ->
                                                uploadError = error.message ?: "Không thể xóa tệp đã tải lên"
                                            }
                                        )
                                    }
                                },
                                enabled = !isUploading && deletingImageIndex == null
                            ) {
                                Text(if (isDeletingThisImage) "Đang xóa..." else "Xóa")
                            }
                        }

                        Text(
                            text = image.url.ifBlank { "Chưa có URL ảnh" },
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )

                        if (index > 0) {
                            TextButton(
                                onClick = {
                                    val updated = data.productImages.toMutableList()
                                    val selected = updated.removeAt(index)
                                    updated.add(0, selected)
                                    onUpdate(data.copy(productImages = reindexProductImages(updated)))
                                },
                                enabled = deletingImageIndex == null
                            ) {
                                Text("Đặt làm ảnh bìa")
                            }
                        }
                    }
                }
            }
        }
    }
}

// ============================================================================
// REUSABLE FORM COMPONENTS
// ============================================================================

@Composable
private fun FormField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    placeholder: String = "",
    keyboardType: KeyboardType = KeyboardType.Text,
    singleLine: Boolean = true,
    maxLines: Int = 1,
    enabled: Boolean = true
) {
    Column {
        Text(
            label,
            style = MaterialTheme.typography.labelMedium,
            fontWeight = FontWeight.SemiBold
        )
        Spacer(modifier = Modifier.height(4.dp))
        OutlinedTextField(
            value = value,
            onValueChange = onValueChange,
            modifier = Modifier.fillMaxWidth(),
            placeholder = { Text(placeholder, fontSize = 12.sp) },
            keyboardOptions = KeyboardOptions(keyboardType = keyboardType),
            singleLine = singleLine,
            maxLines = maxLines,
            shape = RoundedCornerShape(8.dp),
            enabled = enabled
        )
    }
}

@Composable
private fun DropdownField(
    label: String,
    value: String,
    options: List<Pair<String, String>>,
    onSelect: (String) -> Unit
) {
    var expanded by remember { mutableStateOf(false) }
    
    Column {
        Text(
            label,
            style = MaterialTheme.typography.labelMedium,
            fontWeight = FontWeight.SemiBold
        )
        Spacer(modifier = Modifier.height(4.dp))
        Box {
            OutlinedButton(
                onClick = { expanded = true },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(48.dp),
                shape = RoundedCornerShape(8.dp)
            ) {
                Text(value, modifier = Modifier.weight(1f), textAlign = androidx.compose.ui.text.style.TextAlign.Start)
                Icon(Icons.Default.ExpandMore, contentDescription = null)
            }
            
            DropdownMenu(
                expanded = expanded,
                onDismissRequest = { expanded = false },
                modifier = Modifier
                    .fillMaxWidth(0.9f)
                    .heightIn(max = 320.dp)
            ) {
                options.forEach { (displayText, value) ->
                    DropdownMenuItem(
                        text = { Text(displayText) },
                        onClick = {
                            onSelect(value)
                            expanded = false
                        }
                    )
                }
            }
        }
    }
}

@Composable
private fun CheckboxField(
    label: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    description: String = ""
) {
    Column {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .clickable { onCheckedChange(!checked) }
                .padding(8.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Checkbox(
                checked = checked,
                onCheckedChange = onCheckedChange
            )
            Spacer(modifier = Modifier.width(8.dp))
            Column {
                Text(
                    label,
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.SemiBold
                )
                if (description.isNotEmpty()) {
                    Text(
                        description,
                        style = MaterialTheme.typography.bodySmall,
                        color = Color.Gray
                    )
                }
            }
        }
    }
}

private fun CompleteProductFormData.withPrimaryCertificate(certificate: CertificateData): CompleteProductFormData {
    val updated = certificates.toMutableList()
    if (updated.isEmpty()) {
        updated += certificate
    } else {
        updated[0] = certificate
    }
    return copy(certificates = updated)
}

private data class UploadedAssetCleanupTarget(
    val publicId: String,
    val resourceType: String
)

private suspend fun cleanupWizardUploads(
    formData: CompleteProductFormData,
    onDeleteUploadedAsset: suspend (String, String) -> Result<Unit>
): Result<Unit> {
    val assets = buildList {
        formData.certificates.forEach { certificate ->
            certificate.publicId
                ?.takeIf { it.isNotBlank() }
                ?.let { add(UploadedAssetCleanupTarget(it, "image")) }
        }
        formData.productImages.forEach { image ->
            image.publicId
                ?.takeIf { it.isNotBlank() }
                ?.let { add(UploadedAssetCleanupTarget(it, resourceTypeForMedia(image.mediaType))) }
        }
    }.distinctBy { "${it.resourceType}:${it.publicId}" }

    if (assets.isEmpty()) return Result.success(Unit)

    val failures = mutableListOf<String>()
    assets.forEach { asset ->
        onDeleteUploadedAsset(asset.publicId, asset.resourceType).onFailure { error ->
            failures += error.message ?: "Khong the xoa asset ${asset.publicId}"
        }
    }

    return if (failures.isEmpty()) {
        Result.success(Unit)
    } else {
        Result.failure(IllegalStateException(failures.first()))
    }
}

private fun reindexProductImages(images: List<ProductImageData>): List<ProductImageData> {
    return images.mapIndexed { index, image ->
        image.copy(
            mediaType = image.mediaType.ifBlank { "IMAGE" },
            sortOrder = index
        )
    }
}

private fun detectMediaType(file: File): String {
    return when (file.extension.lowercase()) {
        "mp4", "mov", "avi", "webm" -> "VIDEO"
        else -> "IMAGE"
    }
}

private fun resourceTypeForMedia(mediaType: String): String {
    return if (mediaType.equals("VIDEO", ignoreCase = true)) "video" else "image"
}

private fun isStepValid(step: Int, formData: CompleteProductFormData): Boolean {
    return when (step) {
        0 -> formData.productName.isNotBlank() &&
            formData.categoryId.isNotBlank() &&
            formData.unit.isNotBlank() &&
            formData.riskClassification.isNotBlank()
        1 -> formData.contactForPrice || formData.price > 0.0
        2 -> {
            val certificate = formData.certificates.firstOrNull()
            val hasPartialCertificate = certificate != null &&
                (certificate.name.isNotBlank() xor certificate.fileUrl.isNotBlank())
            !hasPartialCertificate
        }
        else -> true
    }
}

private fun isFormComplete(formData: CompleteProductFormData): Boolean {
    return formData.productName.isNotBlank() &&
            formData.categoryId.isNotBlank() &&
            formData.unit.isNotBlank() &&
            formData.riskClassification.isNotBlank() &&
            (formData.contactForPrice || formData.price > 0.0)
}

// ============================================================================
// REUSABLE COMPOSABLE: DatePickerField
// ============================================================================
@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun DatePickerField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    modifier: Modifier = Modifier
) {
    var showDatePicker by remember { mutableStateOf(false) }
    
    // Parse current value if valid
    val currentDate = try {
        if (value.isNotBlank()) LocalDate.parse(value) else LocalDate.now()
    } catch (e: Exception) {
        LocalDate.now()
    }
    
    val datePickerState = rememberDatePickerState(
        initialSelectedDateMillis = currentDate.atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli()
    )
    
    if (showDatePicker) {
        DatePickerDialog(
            onDismissRequest = { showDatePicker = false },
            confirmButton = {
                Button(
                    onClick = {
                        datePickerState.selectedDateMillis?.let { millis ->
                            val selectedDate = java.time.Instant.ofEpochMilli(millis)
                                .atZone(java.time.ZoneId.systemDefault())
                                .toLocalDate()
                            onValueChange(selectedDate.format(DateTimeFormatter.ISO_LOCAL_DATE))
                        }
                        showDatePicker = false
                    }
                ) {
                    Text("OK")
                }
            },
            dismissButton = {
                TextButton(onClick = { showDatePicker = false }) {
                    Text("Hủy")
                }
            }
        ) {
            DatePicker(state = datePickerState)
        }
    }
    
    OutlinedTextField(
        value = value,
        onValueChange = { /* Read-only via date picker */ },
        label = { Text(label) },
        placeholder = { Text("yyyy-MM-dd") },
        modifier = modifier.fillMaxWidth(),
        readOnly = true,
        trailingIcon = {
            IconButton(onClick = { showDatePicker = true }) {
                Icon(Icons.Default.DateRange, contentDescription = "Chọn ngày")
            }
        },
        singleLine = true
    )
}
